CREATE TABLE events (
    id SERIAL PRIMARY KEY,
    year INTEGER NOT NULL,
    circa BOOLEAN NOT NULL,
    description TEXT NOT NULL
);

CREATE TABLE hands (
    id SERIAL PRIMARY KEY,
    session_hash INTEGER NOT NULL
);

CREATE TABLE cards (
    id SERIAL PRIMARY KEY,
    hand_id INTEGER NOT NULL REFERENCES hands (id) ON UPDATE CASCADE ON DELETE CASCADE,
    event_id INTEGER NOT NULL REFERENCES events (id) ON UPDATE CASCADE ON DELETE CASCADE
);